imageTag: v1.0.3-beta8
lake:
  encryptionSecret:
    secret: ""
    secretName: "encryption-secret"
    autoCreateSecret: false
grafana:
  enabled: false
  external:
    url: "http://kube-prometheus-grafana.monitoring.svc.cluster.local:3000"
