---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/marcpires/infra-lhc.git
    targetRevision: feat/35-install-defaults
    path: apps/rabbitmq-operator/manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

