---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-operator
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: https://percona.github.io/percona-helm-charts/
      chart: percona/ps-operator
      targetRevision: "release-pso-1.1.0"
      helm:
        valueFiles:
          - $values/values/mysql-operator/values.yaml
    - repoURL: https://github.com/marcpires/infra-lhc.git
      targetRevision: feat/35-install-defaults
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
