crds:
  full: true

server:
  authModes:
    - client
  # sso:
  #   enabled: true
  #   issuer: https://keycloak.homelab
  #   clientId:
  #     name: argo-server-sso
  #     key:

controller:
  workflowNamespaces:
    - argoworkflows
  mertricsConfig:
    enabled: true

  serviceMonitor:
    enabled: true
    namespace: "monitoring"

  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    ingressClassName: traefik
    hosts:
      - workflows.homelab
    paths:
      - backend:
          service:
            name: argo-workflows-server
            port:
              number: 2746
    tls:
      - hosts:
          - workflows.homelab
