server:
  dev:
    enabled: true
  ingress:
    enabled: true
    ingressClassName: "traefik"
    pathType: Prefix
    hosts:
      - host: hscvault.homelab
        paths:
          - /vault
          - /api
