affinity:
  antiAffinityTopologyKey: "kubernetes.io/hostname"
  advanced:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - orangepi6plus
pmm:
  enabled: true
